ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odom0: /diff_cont/odom
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false]

    imu0: /imu_corrected
    imu0_config: [false, false, false,
                  true, true, false,
                  false, false, false,
                  true, true, true,
                  false, false]

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
